apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mbb3wrbf0-java-springboot
  janus-idp.io/tekton: mbb3wrbf0-java-springboot
  backstage.io/kubernetes-id: mbb3wrbf0-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mbb3wrbf0-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
