apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mbb3wrbf0-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mbb3wrbf0-java-springboot-gitops